image: 'ruby:2.6.3'

services:
  - mysql:5.7

variables:
  MYSQL_DATABASE: 'pj-voucher_test'
  MYSQL_ROOT_PASSWORD: ''
  MYSQL_ALLOW_EMPTY_PASSWORD: 'yes'

stages:
  - check

cache:
  paths:
    - package.json
    - vendor/bundle

before_script:
  - apt-get update -qq && apt-get install -y -qq nodejs
  - gem install bundler --no-document
  - cp config/database.yml.ci config/database.yml
  - bundle install
  - bundle exec rails db:create RAILS_ENV=test
  - bundle exec rails db:schema:load RAILS_ENV=test

rubocop:
  stage: check
  script:
    - bundle exec rubocop

audit:
  stage: check
  script:
    - bundle exec bundle-audit check --update

rspec:
  stage: check
  script:
    - bundle exec rspec

brakeman:
  stage: check
  script:
    - bundle exec brakeman
