PreCommit:
  RuboCop:
    enabled: true
    command: ['bundle', 'exec', 'rubocop', '-c', './.rubocop.yml']
    on_warn: fail # Treat all warnings as failures

  Brakeman:
    enabled: true
    command: ['bundle', 'exec', 'brakeman']
    on_warn: fail

  BundleCheck:
    enabled: true
    on_warn: fail

  BundleAudit:
    enabled: true
    flags: ['--update']
    on_warn: fail

PrePush:
  RSpec:
    enabled: true
    command: ['bundle', 'exec', 'rspec', 'spec']
    on_warn: fail

  BundleInstall:
    enabled: true
    on_warn: fail

PostCheckout:
  ALL: # Special hook name that customizes all hooks of this type
    quiet: true # Change all post-checkout hooks to only display output on failure

  IndexTags:
    enabled: true # Generate a tags file with `ctags` each time HEAD changes
