AllCops:
  Includes:
    - Rakefile
    - config.ru
  Excludes:
    - bin/**
    - db/**
    - config/**
    - script/**
  Documentation:
    Enabled: false
Metrics/LineLength:
  Max: 200
  AllowURI: true
Style/FrozenStringLiteralComment:
  Enabled: false
